# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precendence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by defaul the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
server:
  port: 8081

security:
  basic:
    enabled: "${SECURITY_ENABLED:false}"
  user:
    name: "admin"
    password: "admin"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:false}"

gitlab:
  host: "${GITLAB_HOST:https://gitlab-dev.smarterbalanced.org}"
  user: "${GITLAB_USER}"
  pass: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP:brett-itembank}"
  localBaseDir: "${GITLAB_LOCAL_BASE_DIR:/Users/brettdrainer/ImsGitlabRepo}"


