# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precendence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by defaul the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
server:
  port: 8081

security:
  basic:
    enabled: "${SECURITY_ENABLED:true}"
  user:
    name: "admin"
    password: "admin"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"
  datasource:
    url: "${DB_URL:jdbc:mysql://iat-db.cjqp2fdamfoh.us-east-2.rds.amazonaws.com:3306/iat?useSSL=false}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"

itembank:
  host: "${GITLAB_HOST:https://gitlab-dev.smarterbalanced.org}"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP:iat-development}"
  localBaseDir: "${GITLAB_LOCAL_BASE_DIR:${HOME}/ItemBank}"
  apiVersion: "${GITLAB_API_VERSION:/api/v4}"
  bankKey: "${GITLAB_BANK_KEY:187}"

logging:
  level:
    org:
      opentestsystem:
        ap:
          ims: DEBUG

---
spring:
  profiles: local
  datasource:
    url: "jdbc:mysql://localhost:3306/iat?useSSL=false"
